In [38]:
%%time
from transformers import GPT2LMHeadModel, GPT2Tokenizer

# Load pre-trained GPT2 model and tokenizer
model = GPT2LMHeadModel.from_pretrained("gpt2")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

# Set up the input text
input_text = "The quick brown fox"

# Tokenize the input text
input_ids = tokenizer.encode(input_text, return_tensors="pt")

# Generate the probabilities for the next word
output = model(input_ids)
next_token_logits = output[0][:, -1, :]
print(input_ids)

import torch.nn.functional as F

# Convert logits to probabilities using softmax
probs = F.softmax(next_token_logits, dim=-1)

# Convert probabilities to a list of tuples (word_id, probability)
probs_list = [(i, p.item()) for i, p in enumerate(probs[0])]


n = 10 # replace with the number of words you want to generate
for i in range(n):
    output = model(input_ids)
    next_token_logits = output[0][:, -1, :]
    probs = F.softmax(next_token_logits, dim=-1)
    probs_list = [(i, p.item()) for i, p in enumerate(probs[0])]
    next_word_id = 1234 # replace with your chosen word id
    next_word = tokenizer.decode(next_word_id)
    input_ids = torch.cat([input_ids, torch.tensor([[next_word_id]])], dim=-1)
    print(input_ids)

tensor([[  464,  2068,  7586, 21831]])
tensor([[  464,  2068,  7586, 21831,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234,  1234,  1234,  1234]])
CPU times: user 2.59 s, sys: 1.05 s, total: 3.63 s
Wall time: 4.19 s


In [39]:
%%time
from transformers import GPT2LMHeadModel, GPT2Tokenizer

# Load pre-trained GPT2 model and tokenizer
model = GPT2LMHeadModel.from_pretrained("gpt2")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

# Set up the input text
input_text = "The quick brown fox"

# Tokenize the input text
input_ids = tokenizer.encode(input_text, return_tensors="pt")

# Set up the past state
past = None

# Generate the next n words
n = 10
for i in range(n):
    # Generate the probabilities for the next word
    output = model(input_ids, past_key_values=past)
    next_token_logits = output[0][:, -1, :]
    past = output[1]

    # Convert logits to probabilities using softmax
    probs = F.softmax(next_token_logits, dim=-1)

    # Convert probabilities to a list of tuples (word_id, probability)
    probs_list = [(i, p.item()) for i, p in enumerate(probs[0])]

    # Manually select the next word
    next_word_id = 1234 # replace with your chosen word id
    next_word = tokenizer.decode(next_word_id)

    # Add the next word to the input sequence
    input_ids = torch.cat([input_ids, torch.tensor([[next_word_id]])], dim=-1)
    print(input_ids)


tensor([[  464,  2068,  7586, 21831,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234,  1234,  1234]])
tensor([[  464,  2068,  7586, 21831,  1234,  1234,  1234,  1234,  1234,  1234,
          1234,  1234,  1234,  1234]])
CPU times: user 2.51 s, sys: 1.06 s, total: 3.57 s
Wall time: 4.03 s
